name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  Job:
    uses: artus-cli/.github/.github/workflows/ci.yml@master
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 18]
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}
      ci-script: cov
